const Quotes = [
  "“A lesson without pain is meaningless. That’s because no one can gain without sacrificing something first.” – Edward Elric",
  "“Power comes in response to a need, not a desire.” – Goku",
  "“Forgetting is like a wound. The wound may heal, but it has already left a scar.” – Monkey D. Luffy",
  "“A person grows when he’s able to overcome challenges.” – Gintoki Sakata",
  "“Fear is not evil. It tells you what your weakness is.” – Gildarts Clive",
  "“A hero always arrives late—it’s the villain who shows up on time.” – Saitama",
  "“A heart’s a heavy burden to carry if you don't trust its strength.” – Howl Jenkins Pendragon",
  "“The world isn’t perfect, but it’s there for us trying the best it can.” – Roy Mustang",
  "“A lesson in pain is the fastest way to grow.” – Asta",
  "“Human strength lies not in muscle alone, but in the spirit.” – Erza Scarlet",
  "“I want to be stronger—not just for myself, but for those I care about.” – Tanjiro Kamado",
  "“This world is cruel, yet it’s beautiful.” – Mikasa Ackerman",
  "“Revenge is just the start of a darkness you never escape from.” – Sasuke Uchiha",
  "“Being alone is more painful than any physical wound.” – Naruto Uzumaki",
  "“A sword wields no strength unless the hand that holds it has courage.” – Kirito",
  "“I am justice!” – Light Yagami",
  "“You should enjoy the little detours. To the fullest. Because that’s where you’ll find the things more important than what you want.” – Gintoki Sakata",
  "“There’s no shame in falling down. True shame is to not stand up again.” – All Might",
  "“A king must stand alone even if it costs him everything.” – Gilgamesh",
  "“Surpass your limits. That’s the first step to greatness.” – Yami Sukehiro",
  "“I’ll take a potato chip… and eat it!” – Light Yagami",
  "“Life isn’t a game. If you lose, you die.” – Kaiji Itō",
  "“The strong survive—but only by protecting others.” – Kiyotaka Ayanokōji",
  "“I’m not a hero because I want your approval. I’m a hero because I have to be.” – Izuku Midoriya",
  "“I refuse to let this world break me.” – Levi Ackerman",
  "“Justice will prevail, you say? But of course it will—someone has to make it prevail.” – L",
  "“When you give up, that’s when the game is over.” – Misaki Ayuzawa",
  "“Living is a skill too, Rei. It's the hardest one of all.” – Rei Ayanami",
  "“Hope is like the sun. If you only believe in it when you see it, you'll never make it through the night.” – Homura Akemi",
  "“I hate losing more than anyone.” – Katsuki Bakugo",
  "“Pain makes you grow stronger—don’t avoid it.” – Ken Kaneki",
  "“Let me be your hero—even if I’m not perfect.” – Zero Two",
  "“I’m not running away. I never go back on my word. That’s my nindo!” – Shinji Ikari",
  "“I will become the Pirate King!” – Monkey D. Luffy",
  "“There’s no meaning in killing. Redemption comes from remorse, not rage.” – Kenshin Himura",
  "“You can’t change anything unless you can discard something.” – Armin Arlert",
  "“I am gonna be Hokage and protect everyone!” – Naruto Uzumaki",
  "“My friends are my power—they light the way!” – Natsu Dragneel",
];

export default Quotes
